
services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./commands/run_local.sh" ]
    container_name: user-management
    depends_on:
      testlocal:
        condition: service_healthy
    env_file: variables.env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
    networks:
      - app-network

  testlocal:
    container_name: testlocal
    env_file: variables.env
    image: mysql:8.0.34
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  db_data:

networks:
  app-network:
    driver: bridge